name: zeai_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  font_awesome_flutter: ^10.7.0
  percent_indicator: ^4.2.2
  table_calendar: ^3.0.9
  http: ^1.6.0
  intl: ^0.19.0
  http_parser: ^4.0.2
  image_picker: ^1.1.1
  universal_io: ^2.2.2
  pdf: ^3.10.4
  printing: ^5.11.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  url_launcher: ^6.2.6
  audioplayers: ^6.1.0
  open_filex: ^4.7.0
  path_provider: ^2.0.15
  socket_io_client: ^2.0.3
  livekit_client: ^2.5.4
  flutter_webrtc: ^1.2.1    # UPDATED VERSION
  flutter_dotenv: ^6.0.0
  csv: ^6.0.0
  file_saver: ^0.2.12
  excel: ^4.0.4
  emoji_picker_flutter: ^4.4.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.0

    
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  emoji_picker_flutter: ^4.4.0
    
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/event-png/
    - assets/emp-directory/ 
    - assets/sounds/warning.mp3
    - assets/sounds/alarm.mp3
    - assets/fonts/
  
  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Calibri-Bold.ttf
          weight: 700
    - family: DSEG7
      fonts:
         - asset: assets/fonts/DSEG7Classic-Bold.ttf